version: "3.9"

volumes:
  postgres_data:
    driver: local

services:
  go-postgres:
    image: postgres:latest
    container_name: go-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: gouser
      POSTGRES_PASSWORD: gopass

  go-redis:
    restart: unless-stopped
    image: redis:latest
    container_name: go-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
