name: Docs

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/docs.yaml
      - apis/**

jobs:
  github-actions:
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
    name: Node.js ${{ matrix.node-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Redoc CLI
        run: yarn global add redoc-cli
      - name: Build Docs
        run: redoc-cli build ./apis/gin/docs/swagger.yaml --output ./apis/gin/docs/index.html --title "Hello World API"
      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.GH_PAGES_TOKEN }}
          branch: gh-pages
          folder: ./apis/gin/docs
          clean: true
